# Generated by Django 5.1 on 2025-09-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveloffer',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='traveloffer',
            name='extras_on_spot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveloffer',
            name='extras_pre',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveloffer',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveloffer',
            name='min_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveloffer',
            name='payment_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveloffer',
            name='price_excludes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveloffer',
            name='price_includes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveloffer',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='traveloffer',
            name='single_room_extra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='traveloffer',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveloffer',
            name='standard_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
